#default_language_version:
#  python: python3.7
exclude: ^(dist|build|virtualenv)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.5
    hooks:
      - id: terraform-fmt
        files: '\.tf$'
      - id: terraform-validate
        files: '\.tf$'
